version: '3'
services:
  app:
    container_name: mendelights
    restart: always
    build: ./server
    volumes:
      - ./server:/usr/src/app
    ports:
      - 4000:4000
  # website:
  #     image: php:apache
  #     volumes:
  #         - ./website:/var/www/html
  #     ports:
  #         - 5000:80
