version: '3'
services:
  # client:
  # container_name: mendelights-server
  # restart: always
  # build: ./server
  # volumes:
  #   - ./server:/home/src/app/client
  # ports:
  #   - 3000:3000
  server:
    container_name: mendelights-server
    restart: always
    build: ./server
    volumes:
      - ./server:/home/src/app/server
    ports:
      - 4000:4000
  # website:
  #     image: php:apache
  #     volumes:
  #         - ./website:/var/www/html
  #     ports:
  #         - 5000:80
